version: "2"
run:
  tests: true
linters:
  default: none
  enable:
    - errcheck
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - mnd
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wsl_v5
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 2
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    lll:
      line-length: 132
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "100"
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
      enable:
        - assign-exclusive
      disable:
        - append
        - decl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "ST1000:"
    paths:
      - docs
      - kitlog
      - node_modules
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/togdon
  exclusions:
    generated: lax
    paths:
      - docs
      - kitlog
      - node_modules
      - third_party$
      - builtin$
      - examples$
