// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetFrogNameOKCode is the HTTP code returned for type GetFrogNameOK
const GetFrogNameOKCode int = 200

/*GetFrogNameOK Returns the frog.

swagger:response getFrogNameOK
*/
type GetFrogNameOK struct {

	/*
	  In: Body
	*/
	Payload io.ReadCloser `json:"body,omitempty"`
}

// NewGetFrogNameOK creates GetFrogNameOK with default headers values
func NewGetFrogNameOK() *GetFrogNameOK {

	return &GetFrogNameOK{}
}

// WithPayload adds the payload to the get frog name o k response
func (o *GetFrogNameOK) WithPayload(payload io.ReadCloser) *GetFrogNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get frog name o k response
func (o *GetFrogNameOK) SetPayload(payload io.ReadCloser) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetFrogNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
